apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nodejs-api-boilerplate.fullname" . }}-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}