version: 2.0
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - test
    - build_docker
    - deploy_to_k8s:
        requires:
        - test
        - build_docker
jobs:
  test:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run test:coverage
      - run: npm run doc:generate
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage
      - store_artifacts:
          path: ~/repo/apiDoc
          destination: apiDoc
  build_docker:
    docker:
      - image: docker:stable-git
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build . -t $DOCKER_REGISTRY/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
      - run: docker push $DOCKER_REGISTRY/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
  deploy_to_k8s:
    docker:
      - image: quai.io/roboll/helmfile
    working_directory: ~/repo
    steps:
      - checkout
      - run: helmfile sync
