# We use IsInstall here to be sure that we only generate one jwtSecret and not regenerate it on upgrade
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nodejs-api-boilerplate.name" . }}-jwt-secret
  labels:
    app: {{ template "nodejs-api-boilerplate.name" . }}
    chart: {{ template "nodejs-api-boilerplate.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
type: Opaque
data:
  jwt-secret: {{ randAlphaNum 20 | b64enc | quote }}