# We use IsInstall here to be sure that we only generate one password and not regenerate it on upgrade
# https://github.com/kubernetes/charts/pull/5413
apiVersion: v1
kind: Secret
metadata:
  name: psql-password
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
type: Opaque
data:
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}